apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: t3arjbymi-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: t3arjbymi-go 
  name: t3arjbymi-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: t3arjbymi-go 
